
require 'pry'
require 'httparty'

require_relative 'db_config'
require_relative 'models/user'
require_relative 'models/content'


Content.create(author: 'Scott Barry Kaufman', title: "Using Strategic Vision to Motivate", image: "https://images-na.ssl-images-amazon.com/images/I/61uJftMDa-L._UX250_.jpg", bio: 'Scott Barry Kaufman is scientific director of the Imagination Institute in the Positive Psychology Center at the University of Pennsylvania. He is author of Ungifted: Intelligence Redefined and co-author of the upcoming book Wired to Create: Unraveling the Mysteries of the Creative Mind (with Carolyn Gregoire). Kaufman is also co-founder of The Creativity Post and he hosts The Psychology Podcast.', body: "In a culture obsessed with measuring talent and ability, we often overlook the important role of inspiration. Inspiration awakens us to new possibilities by allowing us to transcend our ordinary experiences and limitations. Inspiration propels a person from apathy to possibility, and transforms the way we perceive our own capabilities. Inspiration may sometimes be overlooked because of its elusive nature. Its history of being treated as supernatural or divine hasn’t helped the situation. But as recent research shows, inspiration can be activated, captured, and manipulated, and it has a major effect on important life outcomes.

Inspiration has three main qualities. Pyschologists Todd M. Thrash and Andrew J. Elliot have noted these core aspects of inspiration: evocation, transcendence, and approach motivation. First, inspiration is evoked spontaneously without intention. Inspiration is also transcendent of our more animalistic and self-serving concerns and limitations. Such transcendence often involves a moment of clarity and awareness of new possibilities. As Thrash and Elliot note, “The heights of human motivation spring from the beauty and goodness that precede us and awaken us to better possibilities.” This moment of clarity is often vivid, and can take the form of a grand vision, or a “seeing” of something one has not seen before (but that was probably always there). Finally, inspiration involves approach motivation, in which the individual strives to transmit, express, or actualize a new idea or vision. According to Thrash and Elliot, inspiration involves both being inspired by something and acting on that inspiration.

Inspired people share certain characteristics. Thrash and Elliot developed the “Inspiration Scale,” which measures the frequency with which a person experiences inspiration in their daily lives. They found that inspired people were more open to new experiences, and reported more absorption in their tasks. “Openness to Experience” often came before inspiration, suggesting that those who are more open to inspiration are more likely to experience it. Additionally, inspired individuals weren’t more conscientious, supporting the view that inspiration is something that happens to you and is not willed. Inspired individuals also reported having a stronger drive to master their work, but were less competitive, which makes sense if you think of competition as a non-transcendent desire to outperform competitors. Inspired people were more intrinsically motivated and less extrinsically motivated, variables that also strongly impact work performance. Inspiration was least related to variables that involve agency or the enhancement of resources, again demonstrating the transcendent nature of inspiration. Therefore, what makes an object inspiring is its perceived subjective intrinsic value, and not how much it’s objectively worth or how attainable it is. Inspired people also reported higher levels of important psychological resources, including belief in their own abilities, self-esteem, and optimism. Mastery of work, absorption, creativity, perceived competence, self-esteem, and optimism were all consequences of inspiration, suggesting that inspiration facilitates these important psychological resources. Interestingly, work mastery also came before inspiration, suggesting that inspiration is not purely passive, but does favor the prepared mind.

Inspiration is not the same as positive affect. Compared to the normal experiences of everyday life, inspiration involves elevated levels of positive affect and task involvement, and lower levels of negative affect. Inspiration is not the same state as positive affect, however. Compared to being in an enthusiastic and excited state, people who enter an inspired state (by thinking of a prior moment they were inspired) reported greater levels of spirituality and meaning, and lower levels of volitional control, controllability, and self-responsibility for their inspiration. Whereas positive affect is activated when someone is making progress toward their immediate, conscious goals, inspiration is more related to an awakening to something new, better, or more important: transcendence of one’s previous concerns.

Inspiration is the springboard for creativity. Inspired people view themselves as more creative and show actual increases in self-ratings of creativity over time. Patent-holding inventors report being inspired more frequently and intensely than non-patent holders, and the higher the frequency of inspiration, the higher the number of patents held. Being in a state of inspiration also predicts the creativity of writing samples across scientific writing, poetry, and fiction (as judged by a panel of fellow students) independent of SAT verbal scores, Openness to Experience, positive affect, specific behaviors (e.g., deleting prior sentences), and aspects of the product quality (e.g., technical merit). Inspired writers are more efficient and productive, and spend less time pausing and more time writing. The link between inspiration and creativity is consistent with the transcendent aspect of inspiration, since creativity involves seeing possibility beyond existing constraints. Importantly, inspiration and effort predict different aspects of an activity. Individuals who exerted more effort writing spent more of their time pausing, deleted more words, wrote more sentences per paragraph, and had better technical merit and use of rhyming in poems, but their work was not considered more creative.

Inspiration facilitates progress toward goals. In a recent study conducted by Marina Milyavskaya and her colleagues, college students were asked to report three goals they intended to accomplish throughout the course of the semester. They then reported on their progress three times a month. Those who scored higher on the Inspiration Scale displayed increased goal progress, and their progress was a result of setting more inspired goals. Therefore, people who were generally more inspired in their daily lives also tended to set inspired goals, which were then more likely to be successfully attained. Importantly, the relationship between inspiration and goal progress was reciprocal: goal progress also predicted future goal inspiration. As the researchers note, “this suggests that goal progress and goal inspiration build on each other to form a cycle of greater goal inspiration and greater goal pursuit.” Finally, inspired individuals reported experiencing more purpose in life and more gratitude.

Inspiration increases well-being. In another study, those who were exposed to Michael Jordan’s greatness experienced higher levels of positive affect, and this increase in positive affect was completely explained by their score on the Inspiration Scale. This inspiration was not transitory though, predicting positive well-being (e.g., positive affect, life satisfaction) three months later! Inspiration was more strongly related to future than to present satisfaction. The extent to which inspiration lasted was explained by self-reported levels of purpose and gratitude in life.

These findings show that inspiration matters a lot, which may cause someone to feel pressure to become inspired and helpless to do so considering the evocative and spontaneous nature of inspiration. The writer Elizabeth Gilbert rightly expresses this concern in her inspiring TED talk. I agree with Gilbert that one should not put pressure on oneself to become inspired. These key scientific findings suggest that inspiration is not willed–it happens. Knowing this should free you from the pressure to make inspiration happen.

This does not mean that inspiration is completely outside your control. Contrary to the view of inspiration as purely mythical or divine, I think inspiration is best thought of as a surprising interaction between your current knowledge and the information you receive from the world. There are things you can do to increase the likelihood of inspiration occurring. Research shows quite clearly that preparation (“work mastery”) is a key ingredient. While inspiration is not the same as effort, effort is an essential condition for inspiration, preparing the mind for an inspirational experience. Openness to Experience and positive affect are also important, as having an open mind and approach-oriented attitude will make it more likely that you will be aware of the inspiration once it arrives. Small accomplishments are also important, as they can boost inspiration, setting off a productive and creative cycle.

Another incredibly important, and often overlooked trigger of inspiration is exposure to inspiring managers, role models, and heroes. As Gregory Dess and Joseph Picken note in “Changing Roles: Leadership In The 21st Century,” our competitive global economy requires leaders to shift their focus from efficient management to effective utilization of a company’s diversity of resources. They argue for five key roles of leadership:

Using strategic vision to motivate and inspire
Empowering employees at all levels
Accumulating and sharing internal knowledge
Gathering and integrating external information
Challenging the status quo and enabling creativity
Steve Jobs is the quintessential example of an inspiring manager, and he undoubtedly checked each of these boxes in spades.

To become personally inspired, the best you can do is set up the optimal circumstances for inspiration. As a society, the best we can do is assist in setting up these important circumstances for everyone. An easy first step is simply recognizing the sheer potency of inspiration, and its potential impact on everything we do.

", media: 'article')

Content.create(author: "Kevin Aitken", title: "Frustration can be good", image: "https://static01.nyt.com/images/2015/07/13/arts/13BOOKSHEER-1436727900014x/13BOOKSHEER-1436727900014-master180.jpg", bio: "Born in 1993", body: "Bring to mind a conflict at work, and you’ll probably have the perpetrator in mind: your incompetent boss, that passive-aggressive colleague, or the resource-hoarding peer in another department. We spend an inordinate amount of time complaining about these people, avoiding them, and fighting with them. But if you want to manage conflict in the workplace, you can’t start with someone else. Usually there isn’t just one culprit, and if you want less fighting and a more enjoyable, productive workplace, you have to understand your own role in it and what you can do to break a vicious cycle that starts with frustration and stress and ends with workplace wars.

Constant challenges breed frustration. A healthy dose of frustration can be good, leading to determination and creativity. Unfortunately, instead of the occasional obstacle at work, we are often buried in an avalanche of problems. We don’t have the resources we need to do our job, and the goalposts keep moving. We blame the relentless, do-more-with-less nature of our shortsighted, quarterly-results-driven business climate for our frustration, or we pin responsibility on unending change or corporate culture. Whatever the reason, many of us are chronically frustrated at work.

Toxic emotions are stressful. Chronic frustration often morphs into fear and anger — “destructive emotions” that serve as an early warning system that we’re in danger. When the alarm rings, our bodies go into high alert, adrenaline and hormones course through our veins, muscles tighten so that we can move quickly, hands sweat, and breathing and heart rates speed up. This would all be well and good if it happened infrequently and saved us from actual danger. Unfortunately, frustration, low-grade fear, irritation, and even rage are familiar companions at work. Many of us are hyperalert all the time. We don’t thrive physically, we are disengaged and unhappy at work, and our brains don’t work properly.

Stress feeds conflict — and conflict breeds anger, resentment, and unhappiness. It’s easy to fool ourselves into thinking that stress isn’t all bad. In fact, when we’re under pressure, we may perform well on routine, well-rehearsed tasks. But when we’re under chronic stress, our complex thinking, reasoning, and social skills all suffer. Our ability to process and use information is compromised, as is our judgment. We have more difficulty with being flexible or open to new ideas, and we start seeing things in simplistic ways. We overreact to minor irritants, and everything and everyone starts looking like a threat. In this state, we are more likely to cause problems than solve them — especially in relationships.

This is when the vicious cycle becomes an endless loop. We don’t think straight. We pick fights. People aren’t pleased, and they let us know. Stress escalates, and our reasoning and behavior suffer even more. We lash out, hide out, or opt out.

A Three-Step Process to Interrupt the Vicious Cycle
If you want to break this cycle and have fewer destructive conflicts at work, the first step is to become more aware of your feelings and reactions to pressure and stress. The second step is to consciously manage your emotions, and the third is to start seeing people as people, not as threats.

Step 1: Develop self-awareness. To interrupt the frustration-stress-conflict cycle, you need to begin by recognizing what causes you to feel thwarted, scared, or threatened and what drives you to the battleground. This sounds easy, but even well-intentioned people typically put self-reflection last on the list — there just aren’t enough hours in the day. Telling yourself you don’t have time or are not inclined to “work on yourself” will keep you stuck in a bunker mentality at work. Instead, make time and tap into curiosity and courage to try to figure out what kinds of situations (and people) send you into the stratosphere. The more you know about your triggers, the better you can control your emotions.

YOU AND YOUR TEAM SERIES
Conflict


How to Have Difficult Conversations When You Don’t Like Conflict
Joel Garfinkle
How Self-Managed Teams Can Resolve Conflict
Amit Maimon
Even Experienced Executives Avoid Conflict
Ron Ashkenas
Step 2: Employ emotional self-control. Once you’re aware of the emotions that are driving your behavior, you can employ another important emotional intelligence competency: emotional self-control. This is what enables us to check and channel our emotions so that we don’t get stuck in a permanent amygdala hijack. We can manage negative feelings, see reality through a clear lens, and stop lashing out when we feel threatened.

Step 3: Build friendships at work. To minimize stress and conflict at work, we need to replace “I, me, mine” with “We, us, ours.” We need to stop seeing each other in terms of what we can get, and replace it with what we can give. This shift would result in less stress and fewer negative emotions. It would also lead to warmer, friendlier relationships — something most people need and want at work.

Developing self-awareness, increasing your emotional self-control, and recharging relationships at work takes commitment, but you don’t have to remake yourself to improve how you deal with strife. Here are a few practical tips to help you with the above steps:

Build mindfulness practices into your daily life. Mindfulness practices like yoga, meditation, deep breathing, and taking a solitary walk are invaluable when it comes to developing self-awareness, learning to manage our emotions, and short-circuiting the stress response. The research is mounting by the day: Even a few minutes of slow, deep breathing several times a day helps us to clear our minds, calm down, and choose our actions more consciously.

", media: "article")
Content.create(author: "Steven Dubner", title: "Freakonomics podcast", image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Stephen_J._Dubner_by_Audrey_S._Bernstein_wiki.jpg", bio: "Stephen J. Dubner (born August 26, 1963) is an American journalist who has written seven books and numerous articles. Dubner is best known as co-author (with economist Steven Levitt) of the pop-economics book Freakonomics: A Rogue Economist Explores the Hidden Side of Everything, and its sequels, SuperFreakonomics (2009), Think Like a Freak (2014), and When to Rob a Bank (2015)", body: "", media: "podcast")
Content.create(author: "Jack Zenger", title: "Buisness and Buddies", image: "http://wliut.com/wp-content/uploads/2016/03/JZ-color-lTorso4-2007-cropped-e1458250418213.jpg", bio: "Jack Zenger is the CEO and Joseph Folkman is the president of Zenger/Folkman, a leadership development consultancy. They are co-authors of the October 2011 HBR article “Making Yourself Indispensable,” and the book How to Be Exceptional: Drive Leadership Success by Magnifying Your Strengths (McGraw-Hill, 2012).", body: "What do top executives want from their leaders? IBM recently asked this question of 1,700 CEOs in 64 countries. The three leadership traits that most mattered were the ability to focus intensely on customer needs, the ability to collaborate with colleagues — and the ability to inspire.

Our own extensive 360° feedback data, which we’ve gathered from just under 50,000 leaders who have been assessed by approximately a half-million colleagues, strongly confirms the importance of inspiring leadership. Of the 16 leadership competencies we most frequently measure, it is clearly the one that stands out. In our data, the ability to inspire creates the highest levels of employee engagement and commitment. It is what most powerfully separates the most effective leaders from the average and least-effective leaders. And it is the factor most subordinates identify when asked what they would most like to have in their leader.

Yet, when you talk with leaders who want to be more inspiring, you often get a deer-in-the-headlights reaction. They simply do not know what to do.

What inspiring leaders do. To address this question we engaged in what some might refer to as a reverse-engineering exercise. We went into our database and looked for those leaders who received the highest scores on the competency of “inspires and motivates to high performance.” We found 1,000 such leaders and then analyzed what they did that separated them from their less-inspiring counterparts.

Some of what they did was specific and tangible. For example, they set stretch goals with their team. They spent time developing their subordinates. They engaged in highly collaborative behavior. They encouraged those about them to be more innovative.

Other things we identified were somewhat less specific and less tangible. These inspirational leaders were more adept at making emotional connections with their subordinates, for instance. They were better at establishing a clear vision. They were more effective in their communication and willing to spend more time communicating. They were ardent champions of change. They were perceived as effective role models within the organization.

Our data send a clear message: In this case, more is more. That is, the more of these behaviors a leader exhibited, the more inspirational that leader is perceived to be.

How they go about it. We next turned our attention from what these inspiring leaders did to the manner in which they did it. We’ve found that many leaders equate being inspirational with being enthusiastic and outgoing, and that can be so, but we also found that leaders could take any number of other approaches that didn’t necessarily require them to be extraverted.

That is, a leader could be inspirational in setting a stretch goal, say, in a number of different ways. She could, for instance, do it by creating a compelling vision (which we dubbed, unsurprisingly, as the “visionary” approach). Alternatively, she could meet with team members and have them, collectively, set the goal (taking what we call an “enhancing” approach.). Another inspiring leader might set stretch goals by tossing out a challenge to the group and setting a specific deadline by which to make it (taking a “driver” approach). Or maybe he encouraged the team to find an ethical goal that focused on the organization’s mission (in which case he took the “principled” route). Yet another of the inspiring leaders might have convened a meeting and delivered a classic half-time locker room speech to set the goal (which we think of as the classical “enthusiast” style) , or finally, he might take the “expert” route and interview team members to determine what skills each might best contribute to the effort.

Inspirational leaders might apply these different approaches to any of their leadership responsibilities, taking, for instance, a visionary approach to championing change by painting a compelling vision of a future in which the company was implementing a new strategy or taking an enhancing approach by encouraging team members to develop an innovative strategy together. Similarly, a leader could go about producing peak results by painting an exciting vision of the future or by marshaling the enthusiasm of the team to aspire to a higher goal.

Although merely 3% took the expert approach, perhaps more surprising is that only 12% went the enthusiast route. Each approach was equally effective, our data indicate, but leaders who were able to master multiple approaches did significantly increase their effectiveness.

Learning to be Inspirational. Finally, we turned our attention to the question of whether leaders could learn to become more inspiring. To find out we did another study of 882 executives from data collected over the last three years, who were measured on the 16 different competencies and encouraged to focus efforts on improving one of them. Focusing on the 310 who chose to improve their ability to inspire others we found that as a group they made impressive strides — moving from the 42nd percentile (that is, below average) to the 70th percentile. This is a statistically significant positive gain, and compelling evidence that when leaders use the right approach they can learn to become more inspiring.

In other words, with awareness, good feedback, and a plan of development, leaders are able to improve this most important of all leadership competencies.

", media: "article")
Content.create(author: "Steven Dubner", title: "Freakonomics podcast II", image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Stephen_J._Dubner_by_Audrey_S._Bernstein_wiki.jpg", bio: "Stephen J. Dubner (born August 26, 1963) is an American journalist who has written seven books and numerous articles. Dubner is best known as co-author (with economist Steven Levitt) of the pop-economics book Freakonomics: A Rogue Economist Explores the Hidden Side of Everything, and its sequels, SuperFreakonomics (2009), Think Like a Freak (2014), and When to Rob a Bank (2015)", body: "", media: "podcast")
Content.create(author: "Joeseph Folkman", title: "Leadership and datasets", image: "http://cdn.timesofisrael.com/uploads/terms-images/writers/Joe-Folkman.jpg", bio: "Zenger Folkman's strengths-based leadership development and coaching programs employ research-based methods that improve organizations and turn good organisations better", body: "A few weeks ago, we were asked to analyze a competency model for leadership development that a client had created. It was based on the idea that at different points in their development, potential leaders need to focus on excelling at different skills. For example, in their model they proposed that a lower-level manager should focus on driving for results while top executives should focus on developing a strategic perspective.

Intuitively, this makes sense, based as it is on the assumption that once people develop a skill, they will continue to exercise it. But, interestingly, we don’t apply it in athletics; athletes continue to practice and develop the same skills throughout their careers.  And as we thought about the excellent senior executives we have met, we observed that they are, in fact, all very focused on delivering results, and many of the best lower level managers are absolutely clear about strategy and vision. This got us to wondering: Are some skills less important for leaders at certain levels of the organization? Or is there a set of skills fundamental to every level?

To see, we compiled a dataset in which we asked 332,860 bosses, peers, and subordinates what skills have the greatest impact on a leader’s success in the position the respondents currently hold. Each respondent selected the top four competencies out of a list of 16 that we provided.We then compared the results for managers at different levels.

As you might expect, the skills people reported needing depended not only on their level in the organization but also on the job they held and their particular circumstances. But even so, there was a remarkable consistency in the data about which skills were perceived as most important in all four levels of the organization we measured.  The same competencies were selected as most important for the supervisors, middle managers, and senior managers alike, and six out of the seven topped the list for top executives. Executives at every organizational level, our respondents reported, need a balance of these competencies. The other nine competencies included in the study were chosen only half as frequently as the top seven.


Find this and other HBR graphics in our VISUAL LIBRARY 
This suggests to us that as people move up the organization, the fundamental skills they need will not dramatically change. Still, our data further indicate, the relative importance of the seven skills does change to some degree as people move up. So, in the graph above the top seven competences are listed in order of importance, as it happens, for the supervisory group. With middle managers, problem solving moves ahead of everything else. Then for senior management, communicating powerfully and prolifically moves to the number two spot. Only for top executives does a new competency enter the mix, as the ability to develop a strategic perspective (which had been moving steadily up the lower ranks) moves into the number five position.

What to make of all this?  From our analysis we conclude that there is some logic to focusing on distinct competencies at different stages of development. But, more fundamentally, it shows us that there are a set of skills that are critical to you throughout your career. And if you wait until you’re a top manager to develop strategic perspective, it will be too late. Lack of a strategic perspective, our research has further indicated, is considered a fatal flaw even when your current job does not require it. Your managers want to see you demonstrate that skill before they promote you.

So it is useful to ask yourself which competencies are most critical for you right now. But it’s also critical to ask yourself which competencies are going to be most critical in the future for the next level job. Demonstrating those skills in your current job provides evidence that you will be successful in the next job.", media: "article")


# <iframe style="border: solid 1px #dedede;"  src="http://app.stitcher.com/splayer/f/11394/50692529" width="220" height="150" frameborder="0" scrolling="no"></iframe>
# <iframe style="border: solid 1px #dedede;"  src="http://app.stitcher.com/splayer/f/11394/50268238" width="220" height="150" frameborder="0" scrolling="no"></iframe>